experiment_params:
  random_state: 42
  test_random_states:
    - 42
    - 123
    - 999
  target_column_name: growth direction
  test_size: 0.4
  corr_threshold: 0.7
  k_best_k: 20
  scoring:
    - accuracy
    - f1_macro
    - precision_macro
    - recall_macro
  logistic_regression_params:
    class_weight: balanced
  svc_params:
    class_weight: balanced
    kernel: poly
  xgboost_params:
